name: seguidor_g
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  provider: ^6.0.5
  intl: ^0.18.1

  # Base de datos SQLite
  sqflite: ^2.3.3
  path: ^1.8.3   # Compatible con tu SDK

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Para generar los archivos .g.dart de los modelos
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
